### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by LilyFoote** [wiktor-k/testresult#11]
I just discovered this via [This Week in Rust](https://this-week-in-rust.org/blog/2024/03/20/this-week-in-rust-539/#projecttooling-updates) and I was able to get this diff on one of my projects:

> 2 files changed, 147 insertions(+), 194 deletions(-)

Going forward it would be helpful to have a changelog for future releases, so it's easier to understand what has changed.

**Comment by wiktor-k** [comment]
That's a good idea, thanks!

Just for the record I try to document bigger changes in tag messages: https://github.com/wiktor-k/testresult/tags
